#!/bin/bash
#
# Automatically add branch name and branch description to every commit message except merge commit.
#
# This is a git hook. Please download and copy to your path_to_git_repo/.git/hooks
# Then chmod 755 path_to_git_repo/.git/hooks/prepare-commit-msg
#
# This works with and without the use of -m

COMMIT_EDITMSG=$1

addBranchName() {
  # fine the branch name
  NAME=$(git branch | grep '*' | sed 's/* //')
  # remove the feaure/ from the front of the branch name
  NAME=${NAME/feature\//}

  #prepend branch name to the commit message
  echo "" >> $COMMIT_EDITMSG
  echo $NAME >> $COMMIT_EDITMSG
  echo $COMMIT_EDITMSGn

}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi
